version: '3.8'

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/generate
    networks:
      - ollama_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama_network

volumes:
  ollama_data:

networks:
  ollama_network: